packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - "@sveltejs/kit@3.0.1"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "esbuild"
  - "prisma"
